"""new fields in user model

Revision ID: 692d9aab7daf
Revises: f7988676abd8
Create Date: 2021-08-05 09:46:26.156027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692d9aab7daf'
down_revision = 'f7988676abd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
